#!/bin/bash
set -euo pipefail

container=$1
shift

export SINGULARITYENV_QBATCH_SYSTEM="container"
export SINGULARITYENV_QBATCH_SCRIPT_FOLDER="magetbrain-container-jobs"
singularity exec --pwd /maget --cleanenv -B $(pwd):/maget --contain ${container} mb $*

for job in $(ls -tr magetbrain-container-jobs/*meta 2>/dev/null || true)
do
  qbatch -n --header "read -r -d '' singularity_script << 'END'"
    --footer "END" --footer "singularity exec --cleanenv -B $(pwd):/maget --contain ${container} \"\${singularity_script}\"" \
	$(cat ${job}) $(dirname ${job})/$(basename ${job} .meta).joblist
done
